apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
  namespace: test-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: ${DOCKER_REPO}:${env.BUILD_NUMBER}
        resources:
          requests:
            memory: "400Mi"
            cpu: "1000m"
          limits:
            memory: "4000Mi"
            cpu: "3000m"
        ports:
          - name: http-port
            containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: test-backend
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 81
  selector:
    app: test

