---
apiVersion: v1
kind: Namespace
metadata:
  name: hgb-backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hgb-backend-deploy
  namespace: hgb-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: test
        image: vulcanos/hgb-be:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "1Gi"
            cpu: "3000m"
        ports:
          - name: http-port
            containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: hgb-backend-service
  namespace: hgb-backend
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 81
  selector:
    app: backend

