---
apiVersion: v1
kind: Service
metadata:
  name: hgb-backend-service
  namespace: hgb-backend
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 81
  selector:
    app: hgb-backend

