package com.devjin.springstu.domain.enums;

import com.devjin.springstu.domain.common.ResponseMessage;
import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum ErrorCode {

    NOT_FOUND(404,"COMMON-ERROR-404", ResponseMessage.FAGE_NOT_FOUND),
    INTER_SERVER_ERROR(500,"COMMON-ERROR-500",ResponseMessage.INTERNAL_SERVER_ERROR),

    ID_DUPLICATION(1001,"USER-ERROR-1001",ResponseMessage.ID_DUPLICATION),
    EMAIL_DUPLICATION(1002,"USER-ERROR-1002",ResponseMessage.EMAIL_DUPLICATION),
    PWD_NOT_VAILD(1003,"USER-ERROR-1003",ResponseMessage.PWD_NOT_VAILD),
    ID_NOT_FOUND(1004,"USER-ERROR-1004",ResponseMessage.ID_NOT_FOUND),
    USER_NOT_SEARCH(1005,"USER-ERROR-1005",ResponseMessage.USER_READ_FAIL),
    USER_UPDATE_FAIL(1006,"USER-ERROR-1006",ResponseMessage.USER_UPDATE_FAIL),
    USER_DELETE_FAIL(1007,"USER-ERROR-1007",ResponseMessage.USER_DELETE_FAIL),
    NOT_FOUND_USER(1008,"USER-ERROR-1008",ResponseMessage.NOT_FOUND_USER),
    USER_VERIFICATIONFAIL(1009,"USER-ERROR-1009",ResponseMessage.USER_VERIFICATION_FAIL),
    PAYMENT_NOT_FOUND(1010,"USER-ERROR-1010",ResponseMessage.PAYMENT_NOT_FOUND),

    USER_CREATE_FAIL(4001,"CREATE-ERROR-4001",ResponseMessage.USER_CREATE_FAIL),
    FILE_DOWNLOAD_FAIL(2001,"FILE-ERROR-2001",ResponseMessage.DOWNLOAD_FAIL),
    LOGIN_FAIL(3001,"LOGIN-ERROR-3001",ResponseMessage.LOGIN_FAIL),

    PRODUCT_KEY_NOT_FOUND(5001,"PRODUCT-ERROR-5001",ResponseMessage.PRODUCT_KEY_NOT_FOUND),
    PRODUCT_KEY_ALREADY_USE(5002,"PRODUCT-ERROR-5002",ResponseMessage.PRODUCT_KEY_ALREADY_USE),
    PRODUCT_KEY_NOT_USE(5003,"PRODUCT-ERROR-5003",ResponseMessage.PRODUCT_KEY_NOT_USE),
    PRODUCT_TYPE_NOT_FOUND(5004,"PRODUCT-ERROR-5004",ResponseMessage.PRODUCT_TYPE_NOT_FOUND),


    PERMISSION_DENIED(6001,"PERMISSION-ERROR-6001",ResponseMessage.PERMISSION_DENIED),
    PERMISSION_DENIED_ID(6002,"PERMISSION-ERROR-6002",ResponseMessage.PERMISSION_DENIED_ID),
    ACCOUNT_NOT_FOUND(6003,"PERMISSION-ERROR-6003",ResponseMessage.ACCOUNT_NOT_FOUND),



    METHOD_NOT_SUPPORT(9001,"METHOD-ERROR-9001",ResponseMessage.METHOD_NOT_SUPPORT),
    MISSING_REQUEST(9002,"METHOD-ERROR-9002",ResponseMessage.MISSING_REQUEST),

    JWT_INVAILDSIGNATURE(-1,"JWT-ERROR-1",ResponseMessage.JWT_INVAILDSIGNATURE),
    JWT_EXPIREDTOKEN(-2,"JWT-ERROR-2",ResponseMessage.JWT_EXPIREDTOKEN),
    JWT_UNSUPPORTTOKEN(-3,"JWT-ERROR-3",ResponseMessage.JWT_UNSUPPORTTOKEN),
    JWT_ILLEGALARGUMENT(-4,"JWT-ERROR-4",ResponseMessage.JWT_ILLEGALARGUMENT),
    JWT_TOKEN_NOT_FOUND(-5,"JWT-ERROR-5",ResponseMessage.JWT_TOKEN_NOT_FOUND),
    JWT_AUTHENTICATION_REQUIRED(-6,"JWT-ERROR-6",ResponseMessage.JWT_AUTHENTICATION_REQUIRED)

    ;


    private int status;
    private String errorCode;
    private String message;

}
